---
# tasks file for ericsysmin.yarn

- name: yarn | Include specific os family tasks
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: yarn | Install yarn package manager
  package: name=yarn state=present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
